
Texture2D<float4> InputOriTexture; // 原图
Texture2D<float4> InputBlurTexture; // 模糊图
RWTexture2D<float4> RWOutputTexture; // 输出结果纹理
SamplerState Sampler; // 用于采样的 SamplerState
StructuredBuffer<int> FisheyeMask;  //遮挡


[numthreads(32, 32, 1)]
void CombineBloomCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    // 获取输入输出纹理的宽高
    uint oriWidth, oriHeight;
    InputOriTexture.GetDimensions(oriWidth, oriHeight);
    uint blurWidth, blurHeight;
    InputBlurTexture.GetDimensions(blurWidth, blurHeight);

    uint outWidth, outHeight;
    RWOutputTexture.GetDimensions(outWidth, outHeight);

    // 当前线程对应的像素坐标
    uint2 pixelCoord = DispatchThreadId.xy;


    float4 oriColor = InputOriTexture[pixelCoord];
    float4 blurColor = InputBlurTexture[pixelCoord];
    int mask = FisheyeMask[pixelCoord.x * oriWidth + pixelCoord.y];

    // 混合颜色：可调整权重
    float oriWeight = 1; // 原图权重
    float blurWeight = 1.0; // 模糊图权重
    float4 outputColor = oriWeight * oriColor + (blurWeight * blurColor) * mask;

    float3 GammaCorrected = pow(outputColor.rgb, 1.0 / 2.2);
    // 写入输出纹理
    RWOutputTexture[pixelCoord] = float4(GammaCorrected.rgb, 0.0);
}
