
// 输入纹理（只读）
Texture2D<float4> InputGaussBlurTexture;
// 输出纹理（可写）
RWTexture2D<float4> RWOutputGaussBlurTexture;
// 高斯模糊一维核
StructuredBuffer<float> GaussBlurKernel1d;
// 用于采样的 SamplerState
SamplerState Sampler; 
// 高斯模糊一维核长度
int BlurLength;
// 模糊方向：0=水平，1=垂直
int BlurDirection;

[numthreads(32, 32, 1)]
void GaussBlur1dCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint outWidth, outHeight;
    RWOutputGaussBlurTexture.GetDimensions(outWidth, outHeight);
    // 当前线程处理的像素坐标
    int2 pixelCoord = uint2(DispatchThreadId.xy);

    // 初始化结果颜色
    float4 resultColor = float4(0, 0, 0, 0);

    // 获取核的半径
    int radius = BlurLength * 0.5;

    // 水平或垂直偏移
    int2 pixelOffset = (BlurDirection == 0) ? int2(1, 0) : int2(0, 1); 

    // 高斯模糊计算
    for (int i = -radius; i <= radius; i++)
    {
        // 计算采样坐标
        int2 offset = int2(pixelOffset * i);
        int2 sampleCoord = pixelCoord + offset;

        float2 UV = float2(sampleCoord.xy + 0.5) / float2(outWidth, outHeight);

        float2 ClampedUV = clamp(UV, float2(0.0, 0.0), float2(1.0, 1.0));

        float4 Sample = InputGaussBlurTexture.SampleLevel(Sampler, ClampedUV, 0);

        float2 TexelOffset = abs(ClampedUV - UV);

        float2 BilinearWeight = saturate(1.0f - TexelOffset);
        // 累加采样值，乘以对应的核值
        float kernelValue = GaussBlurKernel1d[i + radius];
        resultColor +=  BilinearWeight.x * BilinearWeight.y * Sample * kernelValue;
    }
    // 写入结果到输出纹理
    RWOutputGaussBlurTexture[pixelCoord] = resultColor;
}



