

Texture2D<float4> InputMipmapTexture;
RWTexture2D<float4> RWOutputMipmapTexture;
SamplerState InputTextureSampler;

[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);
    float2 Input_ExtentInverse = float2(1 / outwidth, 1 / outheight);

    float2 UV = float2(DispatchThreadId.xy + 0.5) / float2(outwidth, outheight);

	float2 UVs[4];

	UVs[0] = UV + Input_ExtentInverse * float2(-1, -1);
	UVs[1] = UV + Input_ExtentInverse * float2( 1, -1);
	UVs[2] = UV + Input_ExtentInverse * float2(-1, 1);
	UVs[3] = UV + Input_ExtentInverse * float2( 1, 1);

	float4 Sample[4];

	[unroll]
	for(uint i = 0; i < 4; ++i)
	{
        float2 ClampedUV = clamp(UVs[i], float2(0.0,0.0), float2(1.0,1.0));
		Sample[i] = InputMipmapTexture.SampleLevel(InputTextureSampler, ClampedUV, 0);
	}

	float4 OutColor = (Sample[0] + Sample[1] + Sample[2] + Sample[3]) * 0.25f;

	OutColor.rgb = max(float3(0,0,0), OutColor.rgb);

    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}