Texture2D<float4> InputMipmapTexture;
RWTexture2D<float4> RWOutputMipmapTexture;
SamplerState InputTextureSampler;

float Luminance( float3 LinearColor )
{
	return dot( LinearColor, float3( 0.3, 0.59, 0.11 ) );
}

[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy + 0.5) / float2(outwidth, outheight);

	float2 UVs[4];

	UVs[0] = UV + float2(-1, -1) / float2(inwidth, inheight);
	UVs[1] = UV + float2( 1, -1) / float2(inwidth, inheight);
	UVs[2] = UV + float2(-1, 1) / float2(inwidth, inheight);
	UVs[3] = UV + float2( 1, 1) / float2(inwidth, inheight);

	float4 Sample[4];

	[unroll]
	for(uint i = 0; i < 4; ++i)
	{
		Sample[i] = InputMipmapTexture.SampleLevel(InputTextureSampler, UVs[i], 0);
	}

	float4 OutColor = (Sample[0] + Sample[1] + Sample[2] + Sample[3]) * 0.25f;

	OutColor.rgb = max(float3(0,0,0), OutColor.rgb);

    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
