
//#include "/Engine/Private/ACES.ush"
#include "/Engine/Private/Common.ush"
//#include "/Engine/Private/PostProcessCommon.ush"
//#include "/Engine/Private/TonemapCommon.ush"

RWTexture2D<float4> LUTTexture;


static const float3x3 AP0_2_XYZ_MAT =
{
	0.9525523959, 0.0000000000, 0.0000936786,
	0.3439664498, 0.7281660966,-0.0721325464,
	0.0000000000, 0.0000000000, 1.0088251844,
};

static const float3x3 XYZ_2_AP0_MAT =
{
	 1.0498110175, 0.0000000000,-0.0000974845,
	-0.4959030231, 1.3733130458, 0.0982400361,
	 0.0000000000, 0.0000000000, 0.9912520182,
};

static const float3x3 AP1_2_XYZ_MAT = 
{
	 0.6624541811, 0.1340042065, 0.1561876870,
	 0.2722287168, 0.6740817658, 0.0536895174,
	-0.0055746495, 0.0040607335, 1.0103391003,
};

static const float3x3 XYZ_2_AP1_MAT =
{
	 1.6410233797, -0.3248032942, -0.2364246952,
	-0.6636628587,  1.6153315917,  0.0167563477,
	 0.0117218943, -0.0082844420,  0.9883948585,
};

static const float3x3 AP0_2_AP1_MAT = //mul( AP0_2_XYZ_MAT, XYZ_2_AP1_MAT );
{
	 1.4514393161, -0.2365107469, -0.2149285693,
	-0.0765537734,  1.1762296998, -0.0996759264,
	 0.0083161484, -0.0060324498,  0.9977163014,
};

static const float3x3 AP1_2_AP0_MAT = //mul( AP1_2_XYZ_MAT, XYZ_2_AP0_MAT );
{
	 0.6954522414,  0.1406786965,  0.1638690622,
	 0.0447945634,  0.8596711185,  0.0955343182,
	-0.0055258826,  0.0040252103,  1.0015006723,
};

static const float3 AP1_RGB2Y =
{
	0.2722287168, //AP1_2_XYZ_MAT[0][1],
	0.6740817658, //AP1_2_XYZ_MAT[1][1],
	0.0536895174, //AP1_2_XYZ_MAT[2][1]
};

// REC 709 primaries
static const float3x3 XYZ_2_sRGB_MAT =
{
	 3.2409699419, -1.5373831776, -0.4986107603,
	-0.9692436363,  1.8759675015,  0.0415550574,
	 0.0556300797, -0.2039769589,  1.0569715142,
};

static const float3x3 sRGB_2_XYZ_MAT =
{
	0.4124564, 0.3575761, 0.1804375,
	0.2126729, 0.7151522, 0.0721750,
	0.0193339, 0.1191920, 0.9503041,
};

// REC 2020 primaries
static const float3x3 XYZ_2_Rec2020_MAT =
{
	 1.7166084, -0.3556621, -0.2533601,
	-0.6666829,  1.6164776,  0.0157685,
	 0.0176422, -0.0427763,  0.94222867	
};

static const float3x3 Rec2020_2_XYZ_MAT =
{
	0.6369736, 0.1446172, 0.1688585,
	0.2627066, 0.6779996, 0.0592938,
	0.0000000, 0.0280728, 1.0608437
};

// P3, D65 primaries
static const float3x3 XYZ_2_P3D65_MAT =
{
	 2.4933963, -0.9313459, -0.4026945,
	-0.8294868,  1.7626597,  0.0236246,
	 0.0358507, -0.0761827,  0.9570140
};

static const float3x3 P3D65_2_XYZ_MAT =
{
	0.4865906, 0.2656683, 0.1981905,
	0.2289838, 0.6917402, 0.0792762,
	0.0000000, 0.0451135, 1.0438031
};

// Bradford chromatic adaptation transforms between ACES white point (D60) and sRGB white point (D65)
static const float3x3 D65_2_D60_CAT =
{
	 1.01303,    0.00610531, -0.014971,
	 0.00769823, 0.998165,   -0.00503203,
	-0.00284131, 0.00468516,  0.924507,
};

static const float3x3 D60_2_D65_CAT =
{
	 0.987224,   -0.00611327, 0.0159533,
	-0.00759836,  1.00186,    0.00533002,
	 0.00307257, -0.00509595, 1.08168,
};

static const float HALF_MAX = 65504.0;
static const float3x3 GamutMappingIdentityMatrix = { 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 };

static float3 ColorScale = float3(1.0,1.0,1.0);
static float4 OverlayColor = float4(0.00, 0.00, 0.00, 0.000);
static const float LUTSize = 32;
static float4 PostprocessInput0Size = float4(0.10, 61.30057, 816.00, 1.89);
static float4 PostprocessInput1Size = float4(0.00, 0.00, 0.00065, 0.00093);
static float4 PostprocessInput2Size = float4(1.00, 0.01563, 0.0013, 20000.00);
static float4 PostprocessInput3Size = float4(0.00017, 0.52734, 1.8963, 1.8963);
static float4 PostprocessInput4Size = float4(0.35156, -0.50, 0.35156, 0.50);
static float4 PostprocessInput5Size = float4(1.00, 0.00, 0.00, 0.00);
static float4 PostprocessInput6Size = float4(0.00065, 0.00093, 0.70247, 0.99907);
static float4 PostprocessInput7Size = float4(0.00033, 0.00046, 0.7028, 0.99954);
static float4 PostprocessInput8Size = float4(1536.00, 1080.00, 1.00, 0.05);
static float4 PostprocessInput9Size = float4(1.00, 0.00, 0.00, 0.00);
static float4 PostprocessInput10Size = float4(0.00, 0.00, -25246.24805, -25220.00);
static float4 PostprocessInput0MinMax = float4(12.00, 0.10, 2.00, 1.00);
static float4 PostprocessInput1MinMax = float4(0.00, 0.00, -1.001, -1.00);
static float4 PostprocessInput2MinMax = float4(0.00, 1.00, 0.85, 30.00);
static float4 PostprocessInput3MinMax = float4(1.00, -559.99994, -7478.47852, -7470.00);
static float4 PostprocessInput4MinMax = float4(0.35156, -0.50, 0.01471, 0.01471);
static float4 PostprocessInput5MinMax = float4(0.00065, 0.00093, 0.70247, 0.99907);
static float4 PostprocessInput6MinMax = float4(0.0013, 0.00185, 0.0013, 0.00);
static float4 PostprocessInput7MinMax = float4(192.00, 135.00, 0.00521, 0.00741);
static float4 PostprocessInput8MinMax = float4(-1.00, 0.0013, 0.00185, 0.00);
static float4 PostprocessInput9MinMax = float4(0.69987, 0.99537, 0.00, 0.00);
static float4 PostprocessInput10MinMax = float4(0.00, 0.00, 0.99265, 0.99265);
static float4 ViewportSize = float4(1.00, 1.00, 0.00, 0.00);
static uint4 ViewportRect = uint4(1065353215, 0, 0, 0);
static float4 ScreenPosToPixel = float4(0.00, -1.00, 0.00, 0.00);
static float4 SceneColorBufferUVViewport = float4(34.00, 34.00, 1.001, 1.00);
static float3 MappingPolynomial = float3(0.00, 1.00, 0.00);
static float3 InverseGamma = float3(0.45455, 1.00, 1.00);
static float4 ColorMatrixR_ColorCurveCd1 = float4(1.00, 0.00, 0.00, -0.11625);
static float4 ColorMatrixG_ColorCurveCd3Cm3 = float4(0.00, 1.00, 0.00, -0.0054);
static float4 ColorMatrixB_ColorCurveCm2 = float4(0.00, 0.00, 1.00, 1.03);
static float4 ColorCurve_Cm0Cd0_Cd2_Ch0Cm1_Ch3 = float4(0.02709, 0.11286, 0.95124, -0.92632);
static float4 ColorCurve_Ch1_Ch2 = float4(0.02567, -0.02442, 0.00, 0.00);
static float4 ColorShadow_Luma = float4(6.8032, 22.8864, 2.3104, 0.00);
static float4 ColorShadow_Tint1 = float4(1.00, 1.00, 1.00, 0.00);
static float4 ColorShadow_Tint2 = float4(0.00, 0.00, 0.00, 0.00);
static float FilmSlope = 0.91;
static float FilmToe = 0.53;
static float FilmShoulder = 0.23;
static float FilmBlackClip = 0;
static float FilmWhiteClip = 0.035;
static float WhiteTemp = 6500.00;
static float WhiteTint = 0.0;
static float4 ColorSaturation = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorContrast = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGamma = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGain = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorOffset = float4(0.00, 0.00, 0.00, 0.00);
static float4 ColorSaturationShadows = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorContrastShadows = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGammaShadows = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGainShadows = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorOffsetShadows = float4(0.00, 0.00, 0.00, 0.00);
static float4 ColorSaturationMidtones = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorContrastMidtones = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGammaMidtones = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGainMidtones = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorOffsetMidtones = float4(0.00, 0.00, 0.00, 0.00);
static float4 ColorSaturationHighlights = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorContrastHighlights = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGammaHighlights = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorGainHighlights = float4(1.00, 1.00, 1.00, 1.00);
static float4 ColorOffsetHighlights = float4(0.00, 0.00, 0.00, 0.00);
static float ColorCorrectionShadowsMax = 0.09;
static float ColorCorrectionHighlightsMin = 0.50;
static uint OutputDevice = 0;
static uint OutputGamut = 0;
static float BlueCorrection = 0.6;
static float ExpandGamut = 1.0;


float2 D_IlluminantChromaticity( float Temp )
{
	// Correct for revision of Plank's law
	// This makes 6500 == D65
	Temp *= 1.4388 / 1.438;

	float x =	Temp <= 7000 ?
				0.244063 + ( 0.09911e3 + ( 2.9678e6 - 4.6070e9 / Temp ) / Temp ) / Temp :
				0.237040 + ( 0.24748e3 + ( 1.9018e6 - 2.0064e9 / Temp ) / Temp ) / Temp;
	
	float y = -3 * x*x + 2.87 * x - 0.275;

	return float2(x,y);
}


// Accurate for 1000K < Temp < 15000K
// [Krystek 1985, "An algorithm to calculate correlated colour temperature"]
float2 PlanckianLocusChromaticity( float Temp )
{
	float u = ( 0.860117757f + 1.54118254e-4f * Temp + 1.28641212e-7f * Temp*Temp ) / ( 1.0f + 8.42420235e-4f * Temp + 7.08145163e-7f * Temp*Temp );
	float v = ( 0.317398726f + 4.22806245e-5f * Temp + 4.20481691e-8f * Temp*Temp ) / ( 1.0f - 2.89741816e-5f * Temp + 1.61456053e-7f * Temp*Temp );

	float x = 3*u / ( 2*u - 8*v + 4 );
	float y = 2*v / ( 2*u - 8*v + 4 );

	return float2(x,y);
}

float2 PlanckianIsothermal( float Temp, float Tint )
{
	float u = ( 0.860117757f + 1.54118254e-4f * Temp + 1.28641212e-7f * Temp*Temp ) / ( 1.0f + 8.42420235e-4f * Temp + 7.08145163e-7f * Temp*Temp );
	float v = ( 0.317398726f + 4.22806245e-5f * Temp + 4.20481691e-8f * Temp*Temp ) / ( 1.0f - 2.89741816e-5f * Temp + 1.61456053e-7f * Temp*Temp );

	float ud = ( -1.13758118e9f - 1.91615621e6f * Temp - 1.53177f * Temp*Temp ) / Square( 1.41213984e6f + 1189.62f * Temp + Temp*Temp );
	float vd = (  1.97471536e9f - 705674.0f * Temp - 308.607f * Temp*Temp ) / Square( 6.19363586e6f - 179.456f * Temp + Temp*Temp );

	float2 uvd = normalize( float2( u, v ) );

	// Correlated color temperature is meaningful within +/- 0.05
	u += -uvd.y * Tint * 0.05;
	v +=  uvd.x * Tint * 0.05;
	
	float x = 3*u / ( 2*u - 8*v + 4 );
	float y = 2*v / ( 2*u - 8*v + 4 );

	return float2(x,y);
}

float3 xyY_2_XYZ( float3 xyY )
{
	float3 XYZ;
	XYZ[0] = xyY[0] * xyY[2] / max( xyY[1], 1e-10);
	XYZ[1] = xyY[2];  
	XYZ[2] = (1.0 - xyY[0] - xyY[1]) * xyY[2] / max( xyY[1], 1e-10);

	return XYZ;
}


float3x3 ChromaticAdaptation( float2 src_xy, float2 dst_xy )
{
	// Von Kries chromatic adaptation 

	// Bradford
	const float3x3 ConeResponse =
	{
		 0.8951,  0.2664, -0.1614,
		-0.7502,  1.7135,  0.0367,
		 0.0389, -0.0685,  1.0296,
	};
	const float3x3 InvConeResponse =
	{
		 0.9869929, -0.1470543,  0.1599627,
		 0.4323053,  0.5183603,  0.0492912,
		-0.0085287,  0.0400428,  0.9684867,
	};

	float3 src_XYZ = xyY_2_XYZ( float3( src_xy, 1 ) );
	float3 dst_XYZ = xyY_2_XYZ( float3( dst_xy, 1 ) );

	float3 src_coneResp = mul( ConeResponse, src_XYZ );
	float3 dst_coneResp = mul( ConeResponse, dst_XYZ );

	float3x3 VonKriesMat =
	{
		{ dst_coneResp[0] / src_coneResp[0], 0.0, 0.0 },
		{ 0.0, dst_coneResp[1] / src_coneResp[1], 0.0 },
		{ 0.0, 0.0, dst_coneResp[2] / src_coneResp[2] }
	};

	return mul( InvConeResponse, mul( VonKriesMat, ConeResponse ) );
}




float3 WhiteBalance( float3 LinearColor )
{
	float2 SrcWhiteDaylight = D_IlluminantChromaticity( WhiteTemp );
	float2 SrcWhitePlankian = PlanckianLocusChromaticity( WhiteTemp );

	float2 SrcWhite = WhiteTemp < 4000 ? SrcWhitePlankian : SrcWhiteDaylight;
	float2 D65White = float2( 0.31270,  0.32900 );

	{
		// Offset along isotherm
		float2 Isothermal = PlanckianIsothermal( WhiteTemp, WhiteTint ) - SrcWhitePlankian;
		SrcWhite += Isothermal;
	}

	float3x3 WhiteBalanceMat = ChromaticAdaptation( SrcWhite, D65White );
	WhiteBalanceMat = mul( XYZ_2_sRGB_MAT, mul( WhiteBalanceMat, sRGB_2_XYZ_MAT ) );

	return mul( WhiteBalanceMat, LinearColor );
}


float3 ColorCorrect( float3 WorkingColor,
	float4 ColorSaturation,
	float4 ColorContrast,
	float4 ColorGamma,
	float4 ColorGain,
	float4 ColorOffset )
{
	// TODO optimize
	float Luma = dot( WorkingColor, AP1_RGB2Y );
	WorkingColor = max( 0, lerp( Luma.xxx, WorkingColor, ColorSaturation.xyz*ColorSaturation.w ) );
	WorkingColor = pow( WorkingColor * (1.0 / 0.18), ColorContrast.xyz*ColorContrast.w ) * 0.18;
	WorkingColor = pow( WorkingColor, 1.0 / (ColorGamma.xyz*ColorGamma.w) );
	WorkingColor = WorkingColor * (ColorGain.xyz * ColorGain.w) + (ColorOffset.xyz + ColorOffset.w);
	return WorkingColor;
}

// Nuke-style Color Correct
float3 ColorCorrectAll( float3 WorkingColor )
{
	float Luma = dot( WorkingColor, AP1_RGB2Y );

	// Shadow CC
	float3 CCColorShadows = ColorCorrect(WorkingColor, 
		ColorSaturationShadows*ColorSaturation, 
		ColorContrastShadows*ColorContrast, 
		ColorGammaShadows*ColorGamma, 
		ColorGainShadows*ColorGain, 
		ColorOffsetShadows+ColorOffset);
	float CCWeightShadows = 1- smoothstep(0, ColorCorrectionShadowsMax, Luma);
	
	// Highlight CC
	float3 CCColorHighlights = ColorCorrect(WorkingColor, 
		ColorSaturationHighlights*ColorSaturation, 
		ColorContrastHighlights*ColorContrast, 
		ColorGammaHighlights*ColorGamma, 
		ColorGainHighlights*ColorGain, 
		ColorOffsetHighlights+ColorOffset);
	float CCWeightHighlights = smoothstep(ColorCorrectionHighlightsMin, 1, Luma);

	// Midtone CC
	float3 CCColorMidtones = ColorCorrect(WorkingColor, 
		ColorSaturationMidtones*ColorSaturation, 
		ColorContrastMidtones*ColorContrast, 
		ColorGammaMidtones*ColorGamma, 
		ColorGainMidtones*ColorGain, 
		ColorOffsetMidtones+ColorOffset);
	float CCWeightMidtones = 1 - CCWeightShadows - CCWeightHighlights;

	// Blend Shadow, Midtone and Highlight CCs
	float3 WorkingColorSMH = CCColorShadows*CCWeightShadows + CCColorMidtones*CCWeightMidtones + CCColorHighlights*CCWeightHighlights;
	
	return WorkingColorSMH;
}

float3x3 OuputGamutMappingMatrix( uint OutputGamut )
{
	// Gamut mapping matrices used later
	const float3x3 AP1_2_sRGB    = mul( XYZ_2_sRGB_MAT, mul( D60_2_D65_CAT, AP1_2_XYZ_MAT ) );
	const float3x3 AP1_2_DCI_D65 = mul( XYZ_2_P3D65_MAT, mul( D60_2_D65_CAT, AP1_2_XYZ_MAT ) );
	const float3x3 AP1_2_Rec2020 = mul( XYZ_2_Rec2020_MAT, mul( D60_2_D65_CAT, AP1_2_XYZ_MAT ) );

	// Set gamut mapping matrix 
	// 0 = sRGB - D65
	// 1 = P3 - D65
	// 2 = Rec.2020 - D65
	// 3 = ACES AP0 - D60
	// 4 = ACES AP1 - D60

	if( OutputGamut == 1 )
		return AP1_2_DCI_D65;
	else if( OutputGamut == 2 )
		return AP1_2_Rec2020;
	else if( OutputGamut == 3 )
		return AP1_2_AP0_MAT;
	else if( OutputGamut == 4 )
		return GamutMappingIdentityMatrix;
	else
		return AP1_2_sRGB;
}


float3 LogToLin( float3 LogColor )
{
	const float LinearRange = 14;
	const float LinearGrey = 0.18;
	const float ExposureGrey = 444;

	// Using stripped down, 'pure log', formula. Parameterized by grey points and dynamic range covered.
	float3 LinearColor = exp2( ( LogColor - ExposureGrey / 1023.0 ) * LinearRange ) * LinearGrey;
	//float3 LinearColor = 2 * ( pow(10.0, ((LogColor - 0.616596 - 0.03) / 0.432699)) - 0.037584 );	// SLog
	//float3 LinearColor = ( pow( 10, ( 1023 * LogColor - 685 ) / 300) - .0108 ) / (1 - .0108);	// Cineon
	//LinearColor = max( 0, LinearColor );

	return LinearColor;
}

float3 LinToLog( float3 LinearColor )
{
	const float LinearRange = 14;
	const float LinearGrey = 0.18;
	const float ExposureGrey = 444;

	// Using stripped down, 'pure log', formula. Parameterized by grey points and dynamic range covered.
	float3 LogColor = log2(LinearColor) / LinearRange - log2(LinearGrey) / LinearRange + ExposureGrey / 1023.0;	// scalar: 3log2 3mad
	//float3 LogColor = (log2(LinearColor) - log2(LinearGrey)) / LinearRange + ExposureGrey / 1023.0;
	//float3 LogColor = log2( LinearColor / LinearGrey ) / LinearRange + ExposureGrey / 1023.0;
	//float3 LogColor = (0.432699 * log10(0.5 * LinearColor + 0.037584) + 0.616596) + 0.03;	// SLog
	//float3 LogColor = ( 300 * log10( LinearColor * (1 - .0108) + .0108 ) + 685 ) / 1023;	// Cineon
	LogColor = saturate( LogColor );

	return LogColor;
}

half3 ColorCorrection(half3 InLDRColor)
{
	// final color correction to adjust for hardware differences, to make quick adjustements before a demo or simply a user setting
	return MappingPolynomial.x * (InLDRColor * InLDRColor) + MappingPolynomial.y * InLDRColor + MappingPolynomial.z;
}



float rgb_2_saturation( float3 rgb )
{
	float minrgb = min( min(rgb.r, rgb.g ), rgb.b );
	float maxrgb = max( max(rgb.r, rgb.g ), rgb.b );
	return ( max( maxrgb, 1e-10 ) - max( minrgb, 1e-10 ) ) / max( maxrgb, 1e-2 );
}

float rgb_2_yc( float3 rgb, float ycRadiusWeight = 1.75)
{
	// Converts RGB to a luminance proxy, here called YC
	// YC is ~ Y + K * Chroma
	// Constant YC is a cone-shaped surface in RGB space, with the tip on the 
	// neutral axis, towards white.
	// YC is normalized: RGB 1 1 1 maps to YC = 1
	//
	// ycRadiusWeight defaults to 1.75, although can be overridden in function 
	// call to rgb_2_yc
	// ycRadiusWeight = 1 -> YC for pure cyan, magenta, yellow == YC for neutral 
	// of same value
	// ycRadiusWeight = 2 -> YC for pure red, green, blue  == YC for  neutral of 
	// same value.

	float r = rgb[0]; 
	float g = rgb[1]; 
	float b = rgb[2];
  
	float chroma = sqrt(b*(b-g)+g*(g-r)+r*(r-b));

	return ( b + g + r + ycRadiusWeight * chroma) / 3.;
}



float sigmoid_shaper( float x)
{
	// Sigmoid function in the range 0 to 1 spanning -2 to +2.

	float t = max( 1 - abs( 0.5 * x ), 0 );
	float y = 1 + sign(x) * (1 - t*t);
	return 0.5 * y;
}

float glow_fwd( float ycIn, float glowGainIn, float glowMid)
{
   float glowGainOut;

   if (ycIn <= 2./3. * glowMid) {
	 glowGainOut = glowGainIn;
   } else if ( ycIn >= 2 * glowMid) {
	 glowGainOut = 0;
   } else {
	 glowGainOut = glowGainIn * (glowMid / ycIn - 0.5);
   }

   return glowGainOut;
}


// Transformations from RGB to other color representations
float rgb_2_hue( float3 rgb ) 
{
	// Returns a geometric hue angle in degrees (0-360) based on RGB values.
	// For neutral colors, hue is undefined and the function will return a quiet NaN value.
	float hue;
	if (rgb[0] == rgb[1] && rgb[1] == rgb[2])
	{
		//hue = FLT_NAN; // RGB triplets where RGB are equal have an undefined hue
		hue = 0;
	}
	else
	{
		hue = (180. / PI) * atan2(sqrt(3.0)*(rgb[1] - rgb[2]), 2 * rgb[0] - rgb[1] - rgb[2]);
	}

	if (hue < 0.)
		hue = hue + 360;

	return clamp( hue, 0, 360 );
}


float center_hue( float hue, float centerH)
{
	float hueCentered = hue - centerH;
	if (hueCentered < -180.)
		hueCentered += 360;
	else if (hueCentered > 180.)
		hueCentered -= 360;
	return hueCentered;
}



float3  FilmToneMap(  float3  LinearColor )
{
	const float3x3 sRGB_2_AP0 = mul( XYZ_2_AP0_MAT, mul( D65_2_D60_CAT, sRGB_2_XYZ_MAT ) );
	const float3x3 sRGB_2_AP1 = mul( XYZ_2_AP1_MAT, mul( D65_2_D60_CAT, sRGB_2_XYZ_MAT ) );

	const float3x3 AP0_2_sRGB = mul( XYZ_2_sRGB_MAT, mul( D60_2_D65_CAT, AP0_2_XYZ_MAT ) );
	const float3x3 AP1_2_sRGB = mul( XYZ_2_sRGB_MAT, mul( D60_2_D65_CAT, AP1_2_XYZ_MAT ) );

	const float3x3 AP0_2_AP1 = mul( XYZ_2_AP1_MAT, AP0_2_XYZ_MAT );
	const float3x3 AP1_2_AP0 = mul( XYZ_2_AP0_MAT, AP1_2_XYZ_MAT );

	float3 ColorAP1 = LinearColor;
	float3 ColorAP0 = mul( AP1_2_AP0, ColorAP1 );
	const float RRT_GLOW_GAIN = 0.05;
	const float RRT_GLOW_MID = 0.08;

	float saturation = rgb_2_saturation( ColorAP0 );
	float ycIn = rgb_2_yc( ColorAP0 );
	float s = sigmoid_shaper( (saturation - 0.4) / 0.2);
	float addedGlow = 1 + glow_fwd( ycIn, RRT_GLOW_GAIN * s, RRT_GLOW_MID);
	ColorAP0 *= addedGlow;

	const float RRT_RED_SCALE = 0.82;
	const float RRT_RED_PIVOT = 0.03;
	const float RRT_RED_HUE = 0;
	const float RRT_RED_WIDTH = 135;
	float hue = rgb_2_hue( ColorAP0 );
	float centeredHue = center_hue( hue, RRT_RED_HUE );
	float hueWeight = Square( smoothstep( 0, 1, 1 - abs( 2 * centeredHue / RRT_RED_WIDTH ) ) );

	ColorAP0.r += hueWeight * saturation * (RRT_RED_PIVOT - ColorAP0.r) * (1. - RRT_RED_SCALE);

	float3 WorkingColor = mul( AP0_2_AP1_MAT, ColorAP0 );

	WorkingColor = max( 0, WorkingColor );

	WorkingColor = lerp( dot( WorkingColor, AP1_RGB2Y ), WorkingColor, 0.96 );

	const  float  ToeScale = 1 + FilmBlackClip - FilmToe;
	const  float  ShoulderScale = 1 + FilmWhiteClip - FilmShoulder;

	const float InMatch = 0.18;
	const float OutMatch = 0.18;

	float ToeMatch;
	if( FilmToe > 0.8 )
	{

		ToeMatch = ( 1 - FilmToe - OutMatch ) / FilmSlope + log10( InMatch );
	}
	else
	{
		const float bt = ( OutMatch + FilmBlackClip ) / ToeScale - 1;
		ToeMatch = log10( InMatch ) - 0.5 * log( (1+bt)/(1-bt) ) * (ToeScale / FilmSlope);
	}

	float StraightMatch = ( 1 - FilmToe ) / FilmSlope - ToeMatch;
	float ShoulderMatch = FilmShoulder / FilmSlope - StraightMatch;

	float3  LogColor = log10( WorkingColor );
	float3  StraightColor = FilmSlope * ( LogColor + StraightMatch );

	float3  ToeColor = ( -FilmBlackClip ) + (2 * ToeScale) / ( 1 + exp( (-2 * FilmSlope / ToeScale) * ( LogColor - ToeMatch ) ) );
	float3  ShoulderColor = ( 1 + FilmWhiteClip ) - (2 * ShoulderScale) / ( 1 + exp( ( 2 * FilmSlope / ShoulderScale) * ( LogColor - ShoulderMatch ) ) );
	ToeColor = LogColor < ToeMatch ? ToeColor : StraightColor;
	ShoulderColor = LogColor > ShoulderMatch ? ShoulderColor : StraightColor;
	float3  t = saturate( ( LogColor - ToeMatch ) / ( ShoulderMatch - ToeMatch ) );
	t = ShoulderMatch < ToeMatch ? 1 - t : t;
	t = (3-2*t)*t*t;
	float3  ToneColor = lerp( ToeColor, ShoulderColor, t );
	ToneColor = lerp( dot( float3(ToneColor), AP1_RGB2Y ), ToneColor, 0.93 );
	return max( 0, ToneColor );
}

float  LinearToSrgbBranchingChannel( float  lin)
{
	if(lin < 0.00313067) return lin * 12.92;
	return pow(lin, (1.0/2.4)) * 1.055 - 0.055;
}

float3  LinearToSrgbBranching( float3  lin)
{
	return  float3 (
		LinearToSrgbBranchingChannel(lin.r),
		LinearToSrgbBranchingChannel(lin.g),
		LinearToSrgbBranchingChannel(lin.b));
}

float3  LinearToSrgb( float3  lin)
{
	return LinearToSrgbBranching(lin);
}

//这段 CombineLUTsCommon 代码的核心功能是生成用于色调映射（Tone Mapping）和色彩校正的查找表（LUT），
//它通过 HDR 颜色计算 LUT 坐标，并最终输出 LDR 颜色。可以理解为它构造了一张 HDR → LDR 的映射表，然后根据 HDR 颜色获取对应的 LDR 颜色。
float4 CombineLUTsCommon(float2 InUV, uint InLayerIndex)
{
    // 计算LUT索引时的UV坐标，进行半像素偏移，以对齐采样
	float2 UV = InUV - float2(0.5f / LUTSize, 0.5f / LUTSize);

    // 颜色空间转换矩阵定义：
    // 这些矩阵用于不同颜色空间之间的转换
    // 其中，LUTSize 是LUT的大小（32），用于归一化UV和LayerIndex
    float4 Neutral = float4(UV * LUTSize / (LUTSize - 1), InLayerIndex / (LUTSize - 1), 0);

    float4 OutColor = 0;
    //各种矩阵都在ACES.ush
	const float3x3 sRGB_2_AP1 = mul( XYZ_2_AP1_MAT, mul( D65_2_D60_CAT, sRGB_2_XYZ_MAT ) );
	const float3x3 AP1_2_sRGB = mul( XYZ_2_sRGB_MAT, mul( D60_2_D65_CAT, AP1_2_XYZ_MAT ) );
	const float3x3 AP0_2_AP1 = mul( XYZ_2_AP1_MAT, AP0_2_XYZ_MAT );
	const float3x3 AP1_2_AP0 = mul( XYZ_2_AP0_MAT, AP1_2_XYZ_MAT );
    //// 获取到目标输出设备的色域映射矩阵 , OuputGamutMappingMatrix在Engine\Shaders\Private\TonemapCommon.ush
	const float3x3 AP1_2_Output = OuputGamutMappingMatrix( uint(0) );

    // 从Neutral提取LUT编码颜色
	float3 LUTEncodedColor = Neutral.rgb;

    // 将LUT编码颜色转换为线性颜色（Log to Lin）
    //LogToLin和LinToLog都在Engine\Shaders\Private\GammaCorrectionCommon.ush
	float3 LinearColor = LogToLin(LUTEncodedColor) - LogToLin(0);

    // 进行白平衡调整
    //WhiteBalance在Engine\Shaders\Private\PostProcessCombineLUTs.usf
	float3 BalancedColor = WhiteBalance( LinearColor );

    // 将颜色转换到AP1颜色空间
	float3 ColorAP1 = mul(sRGB_2_AP1, BalancedColor);
    // 计算AP1颜色空间的亮度
	float LumaAP1 = dot( ColorAP1, AP1_RGB2Y );
    // 计算颜色的色度分量
	float3 ChromaAP1 = ColorAP1 / LumaAP1;
    // 计算色度距离平方
	float ChromaDistSqr = dot( ChromaAP1 - 1, ChromaAP1 - 1 );
    // 计算扩展色域的影响程度
	float ExpandAmount = ( 1 - exp2( -4 * ChromaDistSqr ) ) * ( 1 - exp2( -4 * ExpandGamut * LumaAP1*LumaAP1 ) );
    // 定义扩展色域的颜色空间变换矩阵
    const float3x3 Wide_2_XYZ_MAT =
    {
        0.5441691, 0.2395926, 0.1666943,
        0.2394656, 0.7021530, 0.0583814,
        -0.0023439, 0.0361834, 1.0552183,
    };
    // 将Wide色域转换到AP1
    const float3x3 Wide_2_AP1 = mul( XYZ_2_AP1_MAT, Wide_2_XYZ_MAT );
    // 计算从AP1到扩展色域的转换矩阵
    const float3x3 ExpandMat = mul( Wide_2_AP1, AP1_2_sRGB );
    // 计算扩展后的颜色
    float3 ColorExpand = mul( ExpandMat, ColorAP1 );
    // 根据ExpandAmount插值扩展色域的影响
    ColorAP1 = lerp( ColorAP1, ColorExpand, ExpandAmount );
    // 应用全局颜色校正
    //ColorCorrectAll在在Engine\Shaders\Private\PostProcessCombineLUTs.usf
	ColorAP1 = ColorCorrectAll( ColorAP1 );
    // 转换回sRGB颜色空间
	float3 GradedColor = mul( AP1_2_sRGB, ColorAP1 );
    // 颜色校正（蓝色通道矫正）
	const float3x3 BlueCorrect =
	{
		0.9404372683, -0.0183068787, 0.0778696104,
		0.0083786969, 0.8286599939, 0.1629613092,
		0.0005471261, -0.0008833746, 1.0003362486
	};
	const float3x3 BlueCorrectInv =
	{
		1.06318, 0.0233956, -0.0865726,
		-0.0106337, 1.20632, -0.19569,
		-0.000590887, 0.00105248, 0.999538
	};

    // AP1颜色空间下的蓝色校正矩阵
	const float3x3 BlueCorrectAP1 = mul( AP0_2_AP1, mul( BlueCorrect, AP1_2_AP0 ) );
	const float3x3 BlueCorrectInvAP1 = mul( AP0_2_AP1, mul( BlueCorrectInv, AP1_2_AP0 ) );
    // 对蓝色通道进行修正
    //BlueCorrection                 0.60                                  1056 float
	ColorAP1 = lerp( ColorAP1, mul( BlueCorrectAP1, ColorAP1 ), BlueCorrection );
    // 应用胶片色调映射
    //FilmToneMap在Engine\Shaders\Private\TonemapCommon.ush
	ColorAP1 = FilmToneMap( ColorAP1 );
    // 逆向蓝色校正
	ColorAP1 = lerp( ColorAP1, mul( BlueCorrectInvAP1, ColorAP1 ), BlueCorrection );
    // 计算最终的sRGB颜色
	float3 FilmColor = max(0, mul( AP1_2_sRGB, ColorAP1 ));
    // 颜色校正
    //ColorCorrection在Engine\Shaders\Private\PostProcessCommon.ush
	FilmColor = ColorCorrection( FilmColor );
    // 应用叠加色
	FilmColor = lerp( FilmColor * ColorScale, OverlayColor.rgb, OverlayColor.a );
    // 应用Gamma校正
    //InverseGamma                   0.45455, 1.00, 1.00                   432 float3
	FilmColor = pow( max(0, FilmColor), InverseGamma.y );
    // 转换到设备颜色空间
	float3  OutDeviceColor = 0;
    float3 OutputGamutColor = FilmColor;
    //LinearToSrgb在Engine\Shaders\Private\GammaCorrectionCommon.ush
    OutDeviceColor = LinearToSrgb( OutputGamutColor );
    // 进行最终颜色输出
	OutColor.rgb = OutDeviceColor / 1.05;
	OutColor.a = 0;
	return OutColor;
}

[numthreads(32, 32, 1)]
void LUTCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint Width, Height;
    LUTTexture.GetDimensions(Width, Height);
    uint2 pixelCoord = DispatchThreadId.xy;
    float2 UV = float2(pixelCoord.xy + 0.5) / float2(Width, Height);
	float4 OutColor = CombineLUTsCommon(UV, 0);
    LUTTexture[pixelCoord] = OutColor;
}