#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

Texture2D<float4> InputTexture[6];
RWTexture2D<float4> RWOutputTexture;
StructuredBuffer<int> SamplePanelID;

struct UnpackedValues {
    int high4;
    int mid14;
    int low14;
};

UnpackedValues UnpackFromInt32(int packed) {
    UnpackedValues result;
    result.high4 = (packed >> 28) & 0xF;
    result.mid14 = (packed >> 14) & 0x3FFF;
    result.low14 = packed & 0x3FFF;
    return result;
}

[numthreads(32, 32, 1)]
void MainCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint height, width;
    // 获取 InputTexture 的宽度和高度
    InputTexture[1].GetDimensions(width, height);
    uint2 pixelCoord = DispatchThreadId.xy;

    // SampleNum = 4
    float4 colors[16];
    int panelIDs[16];
    int panelX[16];
    int panelY[16];
    int coordx;
    int coordy;
    int coordindex;
    //int index = (pixelCoord.y * width + pixelCoord.x) * 16;
    // Load panel IDs and coordinates
    [unroll]
    for (int i = 0; i < 16; ++i)
    {
        switch(SamplePanelID[height * width * 4 * 4])
        {
        case 0:
            //0:16x1
            coordx = pixelCoord.x * 16  + i;
            coordy = pixelCoord.y;
            coordindex = coordy * width * 16 + coordx;
            break;
        case 1:
            //1:8x2
            coordx = pixelCoord.x * 8 + i % 8;
            coordy = pixelCoord.y * 2 + i / 8;
            coordindex = coordy * width * 8 + coordx;
            break;
        case 2:
            //2:4x4
            coordx = pixelCoord.x * 4 + i % 4;
            coordy = pixelCoord.y * 4 + i / 4;
            coordindex = coordy * width * 4 + coordx;
            break;
        case 3:
            //3:2x8
            coordx = pixelCoord.x * 2 + i % 2;
            coordy = pixelCoord.y * 8 + i / 2;
            coordindex = coordy * width * 2 + coordx;
            break;
        case 4:
            //4:1x16
            coordx = pixelCoord.x;
            coordy = pixelCoord.y * 16 + i;
            coordindex = coordy * width + coordx;
            break;
        default:
            //as 16x1
            coordx = pixelCoord.x * 16  + i;
            coordy = pixelCoord.y;
            coordindex = coordy * width * 16 + coordx;
            break;
        }

        UnpackedValues tmp = UnpackFromInt32(SamplePanelID[coordindex]);
        panelIDs[i] = tmp.high4;
        panelX[i] = tmp.mid14;
        panelY[i] = tmp.low14;

    }

    [unroll]
    for (int j = 0; j < 16; ++j)
    {
        int panelID = panelIDs[j];
        int px = panelX[j];
        int py = panelY[j];

        if (panelID == 0)
        {
            colors[j] = InputTexture[1].Load(int3(px, py, 0));
        }
        else if (panelID == 1)
        {
            colors[j] = InputTexture[2].Load(int3(px, py, 0));
        }
        else if (panelID == 2)
        {
            colors[j] = InputTexture[3].Load(int3(px, py, 0));
        }
        else if (panelID == 3)
        {
            colors[j] = InputTexture[4].Load(int3(px, py, 0));
        }
        else if (panelID == 4)
        {
            colors[j] = InputTexture[5].Load(int3(px, py, 0));
        }else
        {
            colors[j] = float4(0, 0, 0, 0);
        }
    }

    // Calculate average color
    float4 averageColor = float4(0, 0, 0, 0);
    [unroll]
    for (int k = 0; k < 16; ++k)
    {
        averageColor += colors[k];
    }
    averageColor /= 16.0;

    RWOutputTexture[DispatchThreadId.xy] = averageColor;
}