#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"


#define DXC_STATIC_DISPATCH_GRID_DIM 0
Texture2D<float4> InputTexture[6];
SamplerState InputTextureSampler;
RWTexture2D<float4> RWOutputTexture;
StructuredBuffer<int> PixelInCircle;
StructuredBuffer<int> SamplePanelID;
StructuredBuffer<int> SamplePanelCoord;
StructuredBuffer<float> SamplePanelBrightness;


int CalculatePixelRealIndex(int2 coord, int BlockSize, int width, int height) {
    int x = coord.x;
    int y = coord.y;

    // 计算当前像素所在的块的行和列
    int BlockRow = x / BlockSize;
    int BlockCol = y / BlockSize;

    // 计算每行的块数
    int BlocksPerRow = (width + BlockSize - 1) / BlockSize;
    int BlocksPerCol = (height + BlockSize - 1) / BlockSize;

    // 计算每行的完美块数
    int BlocksPerfectPerRow = width / BlockSize;
    int BlocksPerfectPerCol = height / BlockSize;

    //计算最末的不完美块长度和宽度
    int BlockUnperfectRow = width - BlocksPerfectPerRow * BlockSize;
    int BlockUnperfectCol = height - BlocksPerfectPerCol * BlockSize;

    // 计算当前像素所在块在 Buff 中的起始位置
    int BlockNumUpper = BlockCol * (BlocksPerfectPerRow * BlockSize * BlockSize + BlockUnperfectRow * BlockSize);
    int BlockNumLeft = (y/BlockSize == BlocksPerfectPerCol ? BlockUnperfectCol : BlockSize) * BlockSize * BlockRow;

    // 计算当前像素在块中的偏移量
    int ElementOffset = (x/BlockSize == BlocksPerfectPerRow ? BlockUnperfectRow : BlockSize) * (y % BlockSize) + (x % BlockSize);

    // 计算 Buff 中的最终下标
    int PixelIndex = BlockNumUpper + BlockNumLeft + ElementOffset;

    return PixelIndex;
}

int Extract4BitFromInt(int res, int index) {
    return (res >> (index * 4)) & 0xF;
}

int Extract16BitFromInt(int res, int index) {
    return (res >> (index * 16)) & 0xFFFF;
}


[numthreads(32, 32, 1)]
void MainCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint height, width;
    InputTexture[1].GetDimensions(width, height);
    uint2 pixelCoord = DispatchThreadId.xy;
    if(PixelInCircle[pixelCoord.y * width + pixelCoord.x] == 0)
    {
        return;
    }

    float4 averageColor = float4(0, 0, 0, 0);
    // Load panel IDs and coordinates
    [unroll]
    for (int i = 0; i < 32; ++i)
    {
        int samplex = (i/2) % 4;
        int sampley = (i/2) / 4;
        //quad and sample 2
        int index = (pixelCoord.y * 4 + sampley) * (4 * width) + (pixelCoord.x * 4 + samplex);
        //linear and sample 2
        //int index =  (pixelCoord.y * width + pixelCoord.x) * 4 * 4 * 2 + i;
        //linear
        //int index =  (pixelCoord.y * width + pixelCoord.x) * 4 * 4 + i;
        //quad
        //int index = (pixelCoord.y * 4 + sampley) * (4 * width) + (pixelCoord.x * 4 + samplex);
        //4bit id
        int idx = pixelCoord.x;
        int idy = pixelCoord.y * 4;
        int Idindex = (idy + i / 8) * width + idx;
        int panelID = Extract4BitFromInt(SamplePanelID[Idindex], i % 8);

        int coordx = pixelCoord.x * 4 * 2 + i % 8;
        int coordy = pixelCoord.y * 4 + i / 8;
        int coordindex = coordy * width * 4 * 2 + coordx;
        int px = Extract16BitFromInt(SamplePanelCoord[coordindex],0);
        int py = Extract16BitFromInt(SamplePanelCoord[coordindex],1);

        switch (panelID)
        {
        case 0:
            averageColor += InputTexture[1].Load(int3(px, py, 0));
            break;
        case 1:
            averageColor += InputTexture[4].Load(int3(px, py, 0));
            break;
        case 2:
            averageColor += InputTexture[5].Load(int3(px, py, 0));
            break;
        case 3:
            averageColor += InputTexture[2].Load(int3(px, py, 0));
            break;
        case 4:
            averageColor += InputTexture[3].Load(int3(px, py, 0));
            break;
        default:
            averageColor += float4(0, 0, 0, 0);
            break;
        }
    }
    RWOutputTexture[DispatchThreadId.xy] = averageColor / 32.0;
}