#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"  

void MainVS(
 in float4 InPosition : ATTRIBUTE0,
 in float2 InUV : ATTRIBUTE1,
 out float2 OutUV : TEXCOORD0,
 out float4 OutPosition : SV_POSITION
 )
{
	OutPosition = InPosition;
	OutUV = InUV;
}

Texture2D srcTexture;
SamplerState srcTextureSampler;

void MainPS(
    in float2 UV : TEXCOORD0,
    in float4 Position : SV_POSITION,
    out float4 OutColor : SV_Target0
    )
{
	OutColor = srcTexture.SampleLevel(srcTextureSampler, UV.xy, 0);
}


