#include "/Engine/Public/Platform.ush"
Texture2D<float4> InputOriTexture;
Texture2D<float4> InputBlurTexture;
Texture2D<float4> InputLUTTexture;
RWTexture2D<float4> RWOutputTexture;
SamplerState Sampler;
StructuredBuffer<float> FisheyeMask;

static const float LinearRange = 14;
static const float LinearGrey = 0.18;
static const float ExposureGrey = 444;

float3 LogToLin( float3 LogColor )
{
	float3 LinearColor = exp2( ( LogColor - ExposureGrey / 1023.0 ) * LinearRange ) * LinearGrey;
	return LinearColor;
}

float3 LinToLog( float3 LinearColor )
{
	float3 LogColor = log2(LinearColor) / LinearRange - log2(LinearGrey) / LinearRange + ExposureGrey / 1023.0;	
	LogColor = saturate( LogColor );
	return LogColor;
}

float4 UnwrappedTexture3DSample( Texture2D Texture, SamplerState Sampler, float3 UVW, float Size )
{
	float IntW = floor( UVW.z * Size - 0.5 );
	float FracW = UVW.z * Size - 0.5 - IntW;

	float U = ( UVW.x + IntW ) / Size;
	float V = UVW.y;

    float4 RG0 = Texture.SampleLevel(Sampler, float2(U, V), 0);
    float4 RG1 = Texture.SampleLevel(Sampler, float2(U + 1.0f / Size, V), 0);

	return lerp(RG0, RG1, FracW);
}


float3  ColorLookupTable( Texture2D LUT, SamplerState Sampler, float3  LinearColor )
{
	float3 LUTEncodedColor = LinToLog( LinearColor + LogToLin( 0 ) );
	float3 UVW = LUTEncodedColor * ((32.0f - 1.0f) / 32.0f) + (0.5f / 32.0f);
	float3 OutDeviceColor = UnwrappedTexture3DSample( LUT, Sampler, UVW, 32 ).rgb;
	return OutDeviceColor * 1.05;
}


[numthreads(32, 32, 1)]
void CombineBloomCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint oriWidth, oriHeight;
    RWOutputTexture.GetDimensions(oriWidth, oriHeight);
    uint2 pixelCoord = DispatchThreadId.xy;

    float2 UV = float2(pixelCoord.xy + 0.5) / float2(oriWidth, oriHeight);

    float4 oriColor = InputOriTexture.SampleLevel(Sampler, UV, 0);
    float4 blurColor = InputBlurTexture.SampleLevel(Sampler, UV, 0);;

    float4 outputColor = 1.0 * oriColor + 0.3 * blurColor;

    outputColor.rgb *= FisheyeMask[pixelCoord.y * oriWidth + pixelCoord.x];

    float  LuminanceForPostProcessAA = dot(outputColor.rgb,  float3 (0.299f, 0.587f, 0.114f));
	outputColor = float4(outputColor.rgb, saturate(LuminanceForPostProcessAA));
    float3  OutDeviceColor = ColorLookupTable(InputLUTTexture, Sampler, outputColor.rgb);
    RWOutputTexture[pixelCoord] = float4(OutDeviceColor.rgb, outputColor.a);
}
