#include "/Engine/Public/Platform.ush"
Texture2D<float4> InputTexture;
Texture2D<float4> InputAddTexture;
RWTexture2D<float4> RWOutputTexture;
StructuredBuffer<float> GaussBlurKernel1d;
SamplerState Sampler;
SamplerState AddSampler;
int BlurLength;
int BlurDirection;

float Luminance(float3 LinearColor)
{
    return dot(LinearColor, float3(0.3, 0.59, 0.11));
}

float4 Texture2DSampleLevel(Texture2D Tex, SamplerState Sampler, float2 UV)
{
    return Tex.SampleLevel(Sampler, UV, 0);
}

float4 SampleFilterTexture(Texture2D Tex, SamplerState Sampler, float2 UV, uint TextureWidth, uint TextureHeight)
{
    float2 Filter_UVViewportBilinearMin = float2(0.0f, 0.0f);
    float2 Filter_UVViewportBilinearMax = float2(1.0f, 1.0f);
    float2 Filter_Extent = float2(1.0f / TextureWidth, 1.0f / TextureHeight);

    float2 ClampedUV = clamp(UV, Filter_UVViewportBilinearMin, Filter_UVViewportBilinearMax);
    float4 Sample = Texture2DSampleLevel(Tex, Sampler, ClampedUV);

    float2 TexelOffset = abs(ClampedUV - UV) * Filter_Extent;
    float2 BilinearWeight = saturate(1.0f - TexelOffset);
    return BilinearWeight.x * BilinearWeight.y * Sample;
}


float4 Upsample(Texture2D Texture, SamplerState Sampler, float2 UV, float2 PixelSize)
{
    const float2 Coords[9] =
    {
        float2(-1.0f, 1.0f), float2(0.0f, 1.0f), float2(1.0f, 1.0f),
        float2(-1.0f, 0.0f), float2(0.0f, 0.0f), float2(1.0f, 0.0f),
        float2(-1.0f, -1.0f), float2(0.0f, -1.0f), float2(1.0f, -1.0f)
    };

    const float Weights[9] =
    {
        0.0625f, 0.125f, 0.0625f,
        0.125f, 0.25f, 0.125f,
        0.0625f, 0.125f, 0.0625f
    };

    float4 Color = float4(0.0f, 0.0f, 0.0f, 0.0f);

    for (int i = 0; i < 9; i++)
    {
        float2 CurrentUV = UV + Coords[i] * PixelSize;
        Color += Weights[i] * Texture2DSampleLevel(Texture, Sampler, CurrentUV);
    }

    return Color;
}

float4 UpsampleTentFilter(Texture2D Texture, SamplerState Sampler, float2 UV, float2 PixelSize)
{
    const float2 Offsets[9] =
    {
        float2(-1.0, 1.0), float2(0.0, 1.0), float2(1.0, 1.0),
        float2(-1.0, 0.0), float2(0.0, 0.0), float2(1.0, 0.0),
        float2(-1.0, -1.0), float2(0.0, -1.0), float2(1.0, -1.0)
    };

    const float Weights[9] =
    {
        1.0 / 16.0, 2.0 / 16.0, 1.0 / 16.0,
        2.0 / 16.0, 4.0 / 16.0, 2.0 / 16.0,
        1.0 / 16.0, 2.0 / 16.0, 1.0 / 16.0
    };

    float4 Color = float4(0, 0, 0, 0);

    for (int i = 0; i < 9; i++)
    {
        float2 SampleUV = UV + Offsets[i] * PixelSize;
        Color += Weights[i] * Texture2DSampleLevel(Texture, Sampler, SampleUV);
    }

    return Color;
}


[numthreads(32, 32, 1)]
void GaussBlur1dAddCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputTexture.GetDimensions(inwidth, inheight);
    uint outWidth, outHeight;
    RWOutputTexture.GetDimensions(outWidth, outHeight);
    uint inaddwidth, inaddheight;
    InputAddTexture.GetDimensions(inaddwidth, inaddheight);
    int2 pixelCoord = uint2(DispatchThreadId.xy);

    float4 resultColor = float4(0, 0, 0, 0);

    int radius = BlurLength * 0.5;

    int2 pixelOffset = (BlurDirection == 0) ? int2(1, 0) : int2(0, 1);

    for (int i = -radius; i <= radius; i++)
    {
        int2 offset = int2(pixelOffset * i);
        int2 sampleCoord = pixelCoord + offset;

        float2 UV = float2(sampleCoord.xy + 0.5) / float2(outWidth, outHeight);

        float4 Sample = SampleFilterTexture(InputTexture, Sampler, UV, inwidth, inheight);

        resultColor += Sample * GaussBlurKernel1d[i + radius];
    }

    float2 uv = float2(pixelCoord.xy + 0.5) / float2(outWidth, outHeight);
    resultColor += SampleFilterTexture(InputAddTexture, AddSampler, uv, inaddwidth, inaddheight);
    RWOutputTexture[pixelCoord] = resultColor;
}
