Texture2D<float4> InputMipmapTexture;
RWTexture2D<float4> RWOutputMipmapTexture;
SamplerState InputTextureSampler;

float Luminance( float3 LinearColor )
{
	return dot( LinearColor, float3( 0.3, 0.59, 0.11 ) );
}

/*
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

	float2 UVs[4];

	UVs[0] = UV + float2(-1, -1) / float2(inwidth, inheight);
	UVs[1] = UV + float2( 1, -1) / float2(inwidth, inheight);
	UVs[2] = UV + float2(-1, 1) / float2(inwidth, inheight);
	UVs[3] = UV + float2( 1, 1) / float2(inwidth, inheight);

	float4 Sample[4];

	[unroll]
	for(uint i = 0; i < 4; ++i)
	{
		Sample[i] = InputMipmapTexture.SampleLevel(InputTextureSampler, UVs[i], 0);
	}

	float4 OutColor = (Sample[0] + Sample[1] + Sample[2] + Sample[3]) * 0.25f;

	OutColor.rgb = max(float3(0,0,0), OutColor.rgb);

    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
*/

/*
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

	float2 UVs[4];

	UVs[0] = UV;
	UVs[1] = UV + float2(1, 0) / float2(inwidth, inheight);
	UVs[2] = UV + float2(0, 1) / float2(inwidth, inheight);
	UVs[3] = UV + float2(1, 1) / float2(inwidth, inheight);

	float4 Sample[4];

	[unroll]
	for(uint i = 0; i < 4; ++i)
	{
		Sample[i] = InputMipmapTexture.SampleLevel(InputTextureSampler, UVs[i], 0);
	}

	float4 OutColor = (Sample[0] + Sample[1] + Sample[2] + Sample[3]) * 0.25f;

	OutColor.rgb = max(float3(0,0,0), OutColor.rgb);

    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
*/


/*
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

    float2 Coords[13] = {
        float2( -1.0f,  1.0f ), float2(  1.0f,  1.0f ),
        float2( -1.0f, -1.0f ), float2(  1.0f, -1.0f ),

        float2(-2.0f, 2.0f), float2( 0.0f, 2.0f), float2( 2.0f, 2.0f),
        float2(-2.0f, 0.0f), float2( 0.0f, 0.0f), float2( 2.0f, 0.0f),
        float2(-2.0f,-2.0f), float2( 0.0f,-2.0f), float2( 2.0f,-2.0f)
    };

    float Weights[13] = {
        // 4 samples
        // (1 / 4) * 0.5f = 0.125f
        0.125f, 0.125f,
        0.125f, 0.125f,

        // 9 samples
        // (1 / 9) * 0.5f
        0.0555555f, 0.0555555f, 0.0555555f,
        0.0555555f, 0.0555555f, 0.0555555f,
        0.0555555f, 0.0555555f, 0.0555555f
    };

    float4 OutColor = float4( 0.0f, 0.0f , 0.0f, 0.0f);

    [UNROLL]
    for( int i = 0; i < 13; i++ )
    {
        float2 CurrentUV = UV + Coords[i] / float2(inwidth, inheight);
        float4 color = InputMipmapTexture.SampleLevel(InputTextureSampler, CurrentUV, 0);
        OutColor += Weights[i] * color;
    }
    
    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
*/

//self edit
/*
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

    float2 Coords[13] = {
        float2( -1.0f,  1.0f ), float2(  1.0f,  1.0f ),
        float2( -1.0f, -1.0f ), float2(  1.0f, -1.0f ),

        float2(-2.0f, 2.0f), float2( 0.0f, 2.0f), float2( 2.0f, 2.0f),
        float2(-2.0f, 0.0f), float2( 0.0f, 0.0f), float2( 2.0f, 0.0f),
        float2(-2.0f,-2.0f), float2( 0.0f,-2.0f), float2( 2.0f,-2.0f)
    };

    float Weights[13] = {
        // 4 samples
        // (1 / 4) * 0.5f = 0.125f
        0.125f, 0.125f,
        0.125f, 0.125f,

        // 9 samples
        // center uv get high weight
        0.05f, 0.05f, 0.05f,
        0.05f, 0.1f, 0.05f,
        0.05f, 0.05f, 0.05f
    };

    float4 OutColor = float4( 0.0f, 0.0f , 0.0f, 0.0f);

    [UNROLL]
    for( int i = 0; i < 13; i++ )
    {
        float2 CurrentUV = UV + Coords[i] / float2(inwidth, inheight);
        float4 color = InputMipmapTexture.SampleLevel(InputTextureSampler, CurrentUV, 0);
        OutColor += Weights[i] * color;
    }
    
    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
} 
*/



/*
//h_2x2_box
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

    float4 OutColor = InputMipmapTexture.SampleLevel(InputTextureSampler, UV, 0);

    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
*/

//h_4x4_box
/*
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

	float2 UVs[4];

	UVs[0] = UV + float2(-1, -1) / float2(inwidth, inheight);
	UVs[1] = UV + float2( 1, -1) / float2(inwidth, inheight);
	UVs[2] = UV + float2(-1, 1) / float2(inwidth, inheight);
	UVs[3] = UV + float2( 1, 1) / float2(inwidth, inheight);

	float4 Sample[4];

	[unroll]
	for(uint i = 0; i < 4; ++i)
	{
		Sample[i] = InputMipmapTexture.SampleLevel(InputTextureSampler, UVs[i], 0);
	}

	float4 OutColor = (Sample[0] + Sample[1] + Sample[2] + Sample[3]) * 0.25f;

	OutColor.rgb = max(float3(0,0,0), OutColor.rgb);

    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
*/

//cod
[numthreads(32, 32, 1)]
void MipmapCS(
    uint3 GroupId : SV_GroupID,
    uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupThreadId : SV_GroupThreadID)
{
    uint inwidth, inheight;
    InputMipmapTexture.GetDimensions(inwidth, inheight);
    uint outwidth, outheight;
    RWOutputMipmapTexture.GetDimensions(outwidth, outheight);

    float2 UV = float2(DispatchThreadId.xy) / float2(outwidth, outheight);

    float2 Coords[13] = {
        float2(-1.0f, -1.0f), float2( 1.0f, -1.0f),
        float2(-1.0f,  1.0f), float2( 1.0f,  1.0f),

        float2(-2.0f, -2.0f), float2( 0.0f, -2.0f), float2( 2.0f, -2.0f),
        float2(-2.0f,  0.0f), float2( 0.0f,  0.0f), float2( 2.0f,  0.0f),
        float2(-2.0f,  2.0f), float2( 0.0f,  2.0f), float2( 2.0f,  2.0f)
    };

    float Weights[13] = {
        // 4 samples
        1.0f/8.0f, 1.0f/8.0f,
        1.0f/8.0f, 1.0f/8.0f,

        // 9 samples
        1.0f/32.0f, 1.0f/16.0f, 1.0f/32.0f,
        1.0f/16.0f, 1.0f/8.0f,  1.0f/16.0f,
        1.0f/32.0f, 1.0f/16.0f, 1.0f/32.0f
    };

    float4 OutColor = float4( 0.0f, 0.0f , 0.0f, 0.0f);

    [UNROLL]
    for( int i = 0; i < 13; i++ )
    {
        float2 CurrentUV = UV + Coords[i] / float2(inwidth, inheight);
        float4 color = InputMipmapTexture.SampleLevel(InputTextureSampler, CurrentUV, 0);
        OutColor += Weights[i] * color;
    }
    
    RWOutputMipmapTexture[DispatchThreadId.xy] = OutColor;
}
